import { makeId } from "../../modules/create_id/create_id.js"
const user_avatar_info = (req,res,next)=>{
    res.locals.avatar_information={
        allow_format:["image/png","image/jpg","image/jpeg"],
        max_size_of_file:2100000,
        custom_avatar:{
            public:true,
            path:'public/Przechwytywanie.PNG',
            type:'TUTAJ MA BYC CUSTOM AVATAR',
            id:makeId(20)
           },
        public_avatars:[
            {
             public:true,
             path:'public/1.png',
             type:'Tavatar',
             id:makeId(20)
            },
            {
            public:true,
            path:'public/2.PNG',
            type:'image/png',
            id:makeId(20)
            },
            {
            public:true,
            path:'public/3.PNG',
            type:'image/png',
            id:makeId(20)
            },
            {
                public:true,
                path:'public/4.PNG',
                type:'image/png',
                id:makeId(20)
               },
        ]
    }
    next()
}
export{user_avatar_info}